name: "Mozilla Observatory"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:
          - app.wire.com
          - wire.com
          - account.wire.com
          - teams.wire.com
    steps:
      - name: Mozilla Observatory
        run: |
          npx observatory-cli ${{ matrix.domain }} --format=report --rescan --attempts=20
          npx observatory-cli ${{ matrix.domain }} --format=report --rescan --attempts=20 --min-score=80 --min-grade=B
