name: "Mozilla Observatory"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:
          - app.wire.com
          - wire.com
          - account.wire.com
          - teams.wire.com
          - wire-teams-staging.zinfra.io
          - wire-teams-dev.zinfra.io
          - wire-account-staging.zinfra.io
    steps:
      - name: Mozilla Observatory
        run: |
          npx observatory-cli ${{ matrix.domain }} --format=report --rescan --attempts=20 --min-score=75 --min-grade=B
