name: "SSL Labs"
on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:
          - app.wire.com
          - wire.com
          - account.wire.com
          - teams.wire.com
          - prod-nginz-https.wire.com
          - prod-nginz-ssl.wire.com
    steps:
    - uses: actions/checkout@v2
    - name: SSL Labs Grade
      run: docker run --read-only --cap-drop all jumanjiman/ssllabs-scan:latest -usecache -grade ${{ matrix.domain }}
    - name: SSL Labs Analysis
      run: |
        docker run --read-only --cap-drop all jumanjiman/ssllabs-scan:latest -usecache ${{ matrix.domain }} > ssllabs.json
        python analyse-ssllabs.py ssllabs.json
